[package]
name = "oxide"
version = "0.1.0"
authors = ["Safet Imamović <https://github.com/SafetImamovic>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "oxide_bin"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.9.4", features = ["serde"] }
anyhow = "1.0.98"
winit = { version = "0.30.12", features = ["android-native-activity"] }
env_logger = "0.11.8"
log = "0.4.27"
wgpu = "26.0.1"
pollster = "0.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wgpu = { version = "26.0.1", features = ["webgl"]}
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = [
    "Document",
    "Window",
    "Element",
]}

