[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "snake_bin"
path = "./src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oxide = {path = "../oxide"}
oxide-macro = {path = "../oxide-macro"}
anyhow = "1.0.99"
env_logger = "0.11.8"
log = "0.4.27"

